<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Cell_02" Id="{c78a8a1b-72c4-4e2b-97da-73ec322d436f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Cell_02 EXTENDS FB_PMLUnit IMPLEMENTS I_UnitState
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
SUPER^();	// a call to the parent class FB_PMLUnit
A_Alarms();]]></ST>
    </Implementation>
    <Folder Name="PML States" Id="{0285f8cc-7f0c-46fa-8f34-a040aed8a29b}" />
    <Folder Name="Unit Code" Id="{07caacf8-1fd3-4ed0-b044-32bfc3331b55}" />
    <Action Name="A_Alarms" Id="{349ac69e-70d1-4f5d-9580-2ffcd9e396a7}" FolderPath="Unit Code\">
      <Implementation>
        <ST><![CDATA[

// probably use the event logger]]></ST>
      </Implementation>
    </Action>
    <Method Name="M_Aborted" Id="{216cfd10-5269-4788-a5c0-3901cecac549}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Aborted
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Aborting" Id="{8d3d780e-e47d-4722-a334-8a9715a90c6e}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Aborting

]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Clearing" Id="{0c3efa14-5798-4922-bb96-c39409d8ba8a}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Clearing
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Complete" Id="{a67a6c9a-4209-40da-b08f-a73fb310234d}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Complete
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Completing" Id="{5981bd91-e313-4fb3-9951-f6114e2097a1}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Completing
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Execute" Id="{16a579bc-2100-4d79-b1a1-2b80ae76b67d}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Held" Id="{56339e1b-7be3-45aa-8030-d69cc1b89997}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Held
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Holding" Id="{0d25192b-30e9-4d3c-b20e-bc8c65988aff}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Holding
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Idle" Id="{f17667da-e220-428c-bba2-339c69ed5b06}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Idle
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Resetting" Id="{5ec1cd00-be3f-4e19-99ae-e4eec2d454fc}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Resetting
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Starting" Id="{627cf1d1-83d1-480b-b7aa-9d3cae17a409}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Starting
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_StateComplete" Id="{f4e2521a-f795-4ed3-a7c0-c5e7094cf14d}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_StateComplete
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbPML_StateMachine.M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Stopped" Id="{e0abc6ad-087e-4e5c-a19c-9f93e6457f3f}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Stopped
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Stopping" Id="{049e68b4-5d73-46b7-940f-d50b9c12386a}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Stopping
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Suspended" Id="{8e0e48cb-9530-4c4e-b17b-0a7e49f79805}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Suspended
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Suspending" Id="{d549e89b-dd02-4ef4-b89f-13f4caaa1bcb}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Suspending
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Undefined" Id="{ccb4a0fb-fb58-4c8d-b3b5-6e82f363a053}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Undefined
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Unholding" Id="{cc472f08-a064-4d20-ba75-efd5ca300fb6}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Unholding
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Unsuspending" Id="{96b04a55-55b9-49ef-bf1f-b022f0ba64d8}" FolderPath="PML States\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD M_Unsuspending
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_StateComplete();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>